### ISSUE TITLE
Clean dataset

### ISSUE THREAD

**Issue by jessepisel** [jessepisel/summer_fellows#12]
Drop Nan's? Figure out how to clean up the dataset so that it can be used. Might checkout Missingno.
3 points

**Comment by VictorFavela** [comment]
Worked on Comp. Type so that it could be usable. Now instead of being a string which varies widely even for wells that use the same system there are new columns to represent the parsed data. 

- Completion Type : The completion that was used (below I will provide notes on the details for completion)

- [Sleeves, P&P, Frac Ports, Repeater Ports, CT] : These are the most common completion types, and each column shows how many of the wells stages are of that type. A lot of times we are not able to tell exactly how many are which but when we can that data will be found here

## Notes on Completion

- After a well is drilled there are two options: make it a producer well or plug it and abandon the well. Completion operations occurr when wanting to move forward with developing the well
- There are steps in well completion: casing, cementing, perforating, gravel packing, and installing a production tree
- Casing
	- Casing is the process of reinforcing the drilled hole so it does not close in on itself. Protects well steam from outside water or sand.
	- There are two types of casing
		- A solid string of steel pipe is used if the formation is firm and will remain that way. 
		- If the formation is not as firm and there is risk of loose sand infiltrating the wellstream the casing is isntalled with a wire mesh screen liner to block sand from entering the wellbore.
- Cementing
	- Cementing is the process of pumping in cement slurry to both fill the space between the casing and the wall and push out the drilling fluids
- There are two types of completion methods used on wells
	- Open-Hole 
		- An open-hole completion is when a well is drilled to the top of a reservoir is not closed at the end. This reduces the cost of casing when reservoir is solid and well known
	- Cased-hole
		- Cased-hole completions do close the end, meaning they require Perforation to allow hydrocarbons to enter the well
- Perforation
	- A perforation gun is run through the well and uses a reservoir locating device to know where to perforate. 
- Sometimes a mixture of the two, no well understood benefit to either
- Siding sleeves is the faster techinque of the two
- Plug and Perf
	- After a cement liner is placed part of it is cleared out and a plug is pumped. Then a perforation gun runs through and perforates the plug. Fracking fluid is run through these holes.
	- There is lots of flexibility, decicison can be made and changed very late into development, essentially before the gun is fired
	- Typically used in cased wells
- Sliding Sleeve
	- Pre-perforated sleeves are used, meaning no perforation gun is needed
	- Sliding sleeves are used to control flow and shut off one or more zones, they can be shifted between full open and closed positions
	- They are placed in the well either mechanically or hydraulically, and typically in open hole wells
- Using Both Techinques 
	- Hybrid systems place ball-actuated frac sleeves along the well starting at the toe, then once the maximum number are placed and spaced out the rest is handled by Plug and Perf techinques.
