### ISSUE TITLE
Pair-wise correlation/scatterplot matrix heatmap

### ISSUE THREAD

**Issue by JWolff98** [jessepisel/summer_fellows#27]
## Where is this model used:
Data Science/Various Disciplines
## What is this model
A matrix that models all combinations of two variables (determining a linear correlation coefficient between them and creating a heatmap in most instances) that showcases potential relations between each of the parameters. A more general approach is to model the two variables as a scatterplots (or histograms).
## How could this be applied to oil
These matrices can be utilized to determine potential relations that emerge when comparing two variables at a time in order to see how the variables interact with each other in multivariate space, in this case variables potentially related to the production of oil. By seeing how the variables interrelate we can get a better understanding of the data in multivariate space and limit the variables being represented.
## Notes
These matrices can also represent more than two dimensions at a time by setting a color gradient and/or size of point as a third dimension/fourth dimension; however, interpretability is a limiting factor. As such, care should be used in representing data with more than 3 dimensions. It should be noted that parsing out particularly scattered data through categorical descriptions (Categories can be determined depending on the dataset. In this case, potentially formation type for example) to reveal underlying plots

**Comment by VictorFavela** [comment]
# Review 1

By Victor Favela , 6/16/20, 10:38am

## Overview

Currently I think these models and graphs are very interesting, especially due to the sheer breadth of variables being analyzed. I think as a very basic jumping off point it can be useful to look at all these relations and then use them to gain further information. My main concern however is that the information provided by this model seems to stop at that.

Because of both the resolution of the graph and the number of variables it is only useful for determining the general shape of the scatter plots. Attempting to add categories only makes the graph even more busy and impossible to closely read. If you want to analyze these more specific correlations I think it would be more beneficial to simply plot the ones you were interested on their own.

Since this notebook and model appears to be best used to get a sense for what interesting correlations might exist, perhaps writing a program that detects this would be interesting. The function could take in a set of X, Y parameters and attempt to fit them to a set of functions and seeing if there is any real correlation there, then running it over all combinations of variables it would display the interesting ones. While I do think the big graph showing all the correlations is interesting it's obvious some have close to zero relation and It would be nice to only display the relevant ones.

## Future Work Suggestions

An important decision that needs to be made for this project is to choose what path it continues to go down: it can remain what it is, a simple jumping off point that gives one general ideas for other notebooks they can begin working on, or it can be enhanced to a systematic program that directly tells you where correlations are found and gives you data to begin working on in future notebooks.
I'm not sure which is the right answer, perhaps trying to systematize it would be more work than it's worth or would simply not be useful. Either way I think as it stands it is a handy graph that should be reference when needed provides a useful outline. There are however a lot of unnecessary graphs as it stands given that they're all essentially the same and their distinctions are too cluttered to tell apart. 

## Rankings:
Clear Definition - A
Shown Corr - A
Shown Error - C
Potential - B
Excitement - B
