### ISSUE TITLE
Choropleth Map 

### ISSUE THREAD

**Issue by SsanyaS14** [jessepisel/summer_fellows#32]
## Where is this model used
Sociology

## What is this model

A choropleth map divides a geographical area with different shadings over one variable. The variable uses color progression from light to dark to highlight a change over a geographical area. This map is used to show a variation or different patterns throughout the area. 

## How could this be applied to oil

This can be used to model a certain feature in relation to oil production. If there is more of a certain feature that has a darker shade than the area that has less of the feature which can allow comparison in oil production. For example, if there is more oil production is lightly shaded areas based on a feature, we can conclude that the less of that feature can allow for more oil production rather than more of that feature in an area. 

## Notes

**Comment by VictorFavela** [comment]
# Review 1

By Victor Favela , 6/15/20, 10:20am

## Overview

I think this model is a very interesting way to visualize data spatially, especially given our data is already split into segments such as long/lat and townships. My main concern however comes in trying to use it to examine the relationship between two variables. While I do think this is possible, I think the current implementation is a bit flawed. 

For viewing one variable this model works perfectly, in fact it is very similar to a heat map or a voronoi map, which I recommend you look into for future work. Being able to see where data is concentrated on a map is a great way to link the location of a well to predict certain variables.

When it comes to viewing two variables and trying to examine how they relate to each other however the current implementation does not seem optimal. Currently by taking the numeric average of two variables you disregard their scale. Taking the average between stages + 12 month cum prod is not going to be accurate when stages range from 0-70 and production ranges from 0-500, the magnitude of one outweighs the other. I think there needs to be an overhaul of how two variable analysis is visualized.

Something that I think may be important as well is that perhaps two variable analysis is just something this model is not meant for, and in fact is better suited as a single variable visualization tool. I think it may be more beneficial to think of this model as a tool we could use in our final model to visualize single variables than try to fit it into something its not meant for. That being said if you find a way to better use this model as a predictor of two variables then by all means prove me wrong.

Some other notes:
- Do not use the OS class. Upload the files you are using onto GitHub and read them directly from the directories. In the same way that instead of importing the cleaned dataset csv from our machines we're able to just do "../CleanedDataset.csv", the same can be done with any file you may need to access. If you need help uploading and determining the location of the files post it on slack and we can help out.
- Using pip install on a notebook is also not recommended, that should be something everyone who reads the notebook does on their machines themselves.
- For completion type Sleeves and P&P are by far the most common, the others are really the outliers. I do think analyzing them is important but maybe analyze them in the order of how common they are just so the first couple maps aren't all blank.

## Future Work Suggestions

I think that this model is very interesting as a visualization tool, however I think a lot of the work you are doing with visualizing correlation and model fitting is better suited as its own notebook. It is very interesting and deserves to be looked at fully, so maybe consider moving that to the map/physical notebook where spatial data is analyzed, and then using the Choropleth map as a handy visualization tool in future work. 

## Rankings:
Clear Definition - A
Shown Corr - B
Shown Error - B
Potential - B
Excitement - B

**Comment by samirabr12** [comment]
This model helps us visualize the data in an interesting way. However, I'm not sure how well it will do during this sprint and the next one, compared to some of the other models we have been analyzing. In addition, even though there might be a way to utilize correlation coefficients, there is no way to incorporate error. This model can only analyze one feature and does not tell us as much about the data compared to some of the other models. The Choropleth Map is a good visualization tool, but not as good of a model for comparing features.

Shown Corr - B
Shown Error - C
Potential - C
Interconnectedness - D
Application - B
