### ISSUE TITLE
Transition Model

### ISSUE THREAD

**Issue by SsanyaS14** [jessepisel/summer_fellows#54]
**Where is the Model used**
Sociology

**What is the Model**
The Transition Model is used to show the transition of a product through different applied stages. It shows the changes in birth and death rate in a population as it changes its demographic stages. This is when a population first emerges and how it reacts to the world. 

**How can it be applied to oil**
We can see the changes over time of oil production whether it be through month 1 - month 12. Additionally, we can see the stages oil production must go through, and different multivariable data being applied to the graph to see the transition over oil production.

**Comment by samirabr12** [comment]
I agree with Sanya, I think that this model is not the best fit for our data. In my opinion, it does not really tell us much about how different features affect oil production and how variables affect each other. I also like the Parallel Coordinates model better because it is interactive and easy to interpret in comparison to the Transition Model.

**Comment by samirabr12** [comment]
I agree with what was mentioned in the notebook: this model would be better utilized as a visualization tool rather than a model. Personally, I liked the Parallel Coordinate plot that was created during the Background Research week; it was interactive and provided a better analysis of the data. In addition, I know that the spearman correlation coefficient was calculated, but I don't think it was used in the model. Furthermore, there is no way to calculate error because it is not an estimation model. Therefore, this model could be a part of the visualization section of our project.

Shown Corr - B
Shown Error - D
Potential - C
Interconnectedness - D
Application - C
